version: "3.9"

services:
  xtreamui-main:
    image: xtreamui-core:latest
    container_name: xtreamui-main
    shm_size: '4096'
    privileged: true    
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
      - "1935:1935"
      - "2095:2095"
      - "2096:2096"
    volumes:
      - xtreamui_core:/home/xtreamcodes/iptv_xtream_codes
      - xtreamui_utils:/home/utils
    ulimits:
      nofile:
        soft: 655350
        hard: 655350
      nproc: 655350

volumes:
  xtreamui_core:
    driver: local
  xtreamui_utils:
    driver: local

networks:
  default:
    name: xtreamui_net
    driver: bridge
