version: "3.9"

services:
  xtreamui-main:
    image: xtreamui-core:latest
    container_name: xtreamui-main
    shm_size: '4G'
    privileged: true    
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo

    ulimits:
      nofile:
        soft: 2147483584
        hard: 2147483584
      nproc:
        soft: 2147483584
        hard: 2147483584

    sysctls:
      net.ipv4.tcp_congestion_control: "bbr"
      net.core.default_qdisc: "fq"
      net.core.somaxconn: "65535"
      net.core.netdev_max_backlog: "250000"
      net.core.optmem_max: "65535"
      net.core.netdev_budget: "6000"
      net.core.netdev_budget_usecs: "20000"
      net.ipv4.tcp_max_tw_buckets: "1440000"
      net.ipv4.tcp_max_syn_backlog: "65535"
      net.ipv4.ip_local_port_range: "1024 65000"
      net.ipv4.ip_forward: "1"
      net.ipv4.tcp_no_metrics_save: "1"
      net.ipv4.tcp_slow_start_after_idle: "0"
      net.ipv4.tcp_fin_timeout: "15"
      net.ipv4.tcp_keepalive_time: "300"
      net.ipv4.tcp_keepalive_probes: "5"
      net.ipv4.tcp_keepalive_intvl: "15"
      net.ipv4.tcp_timestamps: "1"
      net.ipv4.tcp_window_scaling: "1"
      net.ipv4.tcp_mtu_probing: "1"
      net.ipv6.conf.all.disable_ipv6: "1"
      net.ipv6.conf.default.disable_ipv6: "1"
      net.ipv6.conf.lo.disable_ipv6: "1"
      net.netfilter.nf_conntrack_max: "8000000"        

    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:2095:2095"
      - "0.0.0.0:2096:2096"

    volumes:
      - xtreamui_core:/home/xtreamcodes/iptv_xtream_codes
      - xtreamui_utils:/home/utils

volumes:
  xtreamui_core:
    driver: local
  xtreamui_utils:
    driver: local

networks:
  default:
    name: xtreamui_network
    driver: bridge
