version: "3.9"

services:
  xtreamui-main:
    image: xtreamui-core:latest
    container_name: xtreamui-main
    shm_size: '4096'
    privileged: true    
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    ulimits:
      nofile:
        soft: 2147483584
        hard: 2147483584      
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:2095:2095"
      - "0.0.0.0:2096:2096"
    volumes:
      - xtreamui_core:/home/xtreamcodes/iptv_xtream_codes
      - xtreamui_utils:/home/utils

volumes:
  xtreamui_core:
    driver: local
  xtreamui_utils:
    driver: local

networks:
  default:
    name: xtreamui_network
    driver: bridge
