#!/bin/bash

SCRIPT=/home/xtreamcodes/iptv_xtream_codes
USER=$(whoami)

if [[ $USER != "root" ]]; then
  echo "Please run as root!"
  exit 0
fi

start() {
  pids=$(pgrep -u xtreamcodes nginx | wc -l)
  if [ $pids != 0 ]; then
    echo 'xtreamcodes is already running'
    return 1
  fi
  echo 'Starting xtreamcodes...'

  kill $(ps aux | grep 'xtreamcodes' | grep -v grep | grep -v '/home/xtreamcodes/iptv_xtream_codes/service' | awk '{print $2}') 2>/dev/null
  sleep 1
  kill $(ps aux | grep 'xtreamcodes' | grep -v grep | grep -v '/home/xtreamcodes/iptv_xtream_codes/service' | awk '{print $2}') 2>/dev/null
  sleep 1
  kill $(ps aux | grep 'xtreamcodes' | grep -v grep | grep -v '/home/xtreamcodes/iptv_xtream_codes/service' | awk '{print $2}') 2>/dev/null
  sleep 2

  sudo -u xtreamcodes /home/xtreamcodes/iptv_xtream_codes/php/bin/php /home/xtreamcodes/iptv_xtream_codes/crons/setup_cache.php
  sudo -u xtreamcodes /home/xtreamcodes/iptv_xtream_codes/php/bin/php /home/xtreamcodes/iptv_xtream_codes/tools/signal_receiver.php >/dev/null 2>/dev/null &
  sudo -u xtreamcodes /home/xtreamcodes/iptv_xtream_codes/php/bin/php /home/xtreamcodes/iptv_xtream_codes/tools/pipe_reader.php >/dev/null 2>/dev/null &
  chown -R xtreamcodes:xtreamcodes /sys/class/net
  chown -R xtreamcodes:xtreamcodes /home/xtreamcodes >/dev/null 2>/dev/null
  sleep 1
  start-stop-daemon --start --quiet --pidfile /home/xtreamcodes/iptv_xtream_codes/php/1.pid --exec /home/xtreamcodes/iptv_xtream_codes/php/sbin/php-fpm -- --daemonize --fpm-config /home/xtreamcodes/iptv_xtream_codes/php/etc/1.conf
  start-stop-daemon --start --quiet --pidfile /home/xtreamcodes/iptv_xtream_codes/php/2.pid --exec /home/xtreamcodes/iptv_xtream_codes/php/sbin/php-fpm -- --daemonize --fpm-config /home/xtreamcodes/iptv_xtream_codes/php/etc/2.conf
  start-stop-daemon --start --quiet --pidfile /home/xtreamcodes/iptv_xtream_codes/php/3.pid --exec /home/xtreamcodes/iptv_xtream_codes/php/sbin/php-fpm -- --daemonize --fpm-config /home/xtreamcodes/iptv_xtream_codes/php/etc/3.conf
  start-stop-daemon --start --quiet --pidfile /home/xtreamcodes/iptv_xtream_codes/php/4.pid --exec /home/xtreamcodes/iptv_xtream_codes/php/sbin/php-fpm -- --daemonize --fpm-config /home/xtreamcodes/iptv_xtream_codes/php/etc/4.conf
  sleep 3
  chmod +x /home/xtreamcodes/iptv_xtream_codes/nginx_rtmp/sbin/nginx_rtmp
  /home/xtreamcodes/iptv_xtream_codes/nginx_rtmp/sbin/nginx_rtmp
  sleep 1
  chmod +x /home/xtreamcodes/iptv_xtream_codes/nginx/sbin/nginx
  /home/xtreamcodes/iptv_xtream_codes/nginx/sbin/nginx
  echo 'Running in foreground...'
  sleep infinity
}

stop() {
  pids=$(pgrep -u xtreamcodes nginx | wc -l)
  if [[ $pids = 0 ]]; then
    echo 'xtreamcodes is not running'
    return 1
  fi
  echo 'Stopping xtreamcodes...'
  sudo killall -u xtreamcodes
  sleep 1
  sudo killall -u xtreamcodes
  sleep 1
  sudo killall -u xtreamcodes
  sleep 1
  kill $(ps aux | grep 'xtreamcodes' | grep -v grep | grep -v '/home/xtreamcodes/iptv_xtream_codes/service' | awk '{print $2}') 2>/dev/null
  sleep 1
  kill $(ps aux | grep 'xtreamcodes' | grep -v grep | grep -v '/home/xtreamcodes/iptv_xtream_codes/service' | awk '{print $2}') 2>/dev/null
  sleep 1
  kill $(ps aux | grep 'xtreamcodes' | grep -v grep | grep -v '/home/xtreamcodes/iptv_xtream_codes/service' | awk '{print $2}') 2>/dev/null
  sleep 2

}

restart() {
  stop
  #ps -U xtreamcodes | egrep -v "ffmpeg|PID" | awk '{print $1}' | xargs kill -9
  start
}

reload() {
  pids=$(pgrep -u xtreamcodes nginx | wc -l)
  if [[ $pids = 0 ]]; then
    echo 'xtreamcodes nginx is not running'
    return 1
  fi
  echo 'Reloading nginx config for xtreamcodes...'
  /home/xtreamcodes/iptv_xtream_codes/nginx/sbin/nginx -s reload
  /home/xtreamcodes/iptv_xtream_codes/nginx_rtmp/sbin/nginx_rtmp -s reload
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  reload)
    reload
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
esac

exit 0